### PR TITLE
Version from sources

### PR DESCRIPTION
**Pull request by dooreelko**
second attempt :) getting used to the github.
i'm creating a new PR as i've stupidly merged the branch into master and have no desire rewriting history. please feel free to delete the original PR after our discussion there is over.

btw. are you recursively traversing the directory until you find the .terraform-version? in that case the -R in grep is probably not a good idea.

what do you think?

### CODE REVIEW

**Comment by dooreelko** [comment]
Third attempt.
Now there's an explicit command `min-required` for tfenv install. No magic. No side effects. Good.

**Comment by dooreelko** [comment]
Just realised the tfenv install doesn't automatically switch the version, thus added min-required to tfenv use

**Comment by dooreelko** [comment]
Hey. Just realised this hangs for a while now and I totally forgot about it, so probably did you. Any thoughts on it?

**Comment by kamatama41** [comment]
@dooreelko 
Sorry, I was busy and forgot as well.
will review soon 🙇

**Comment by kamatama41** [comment]
I've reviewed and confirmed it works fine in the basic usage but doesn't work in tricky situations.
For example, even when a line of `required_version` is commented such as the following, `0.10.1` is chosen.

```hcl
terraform {
//  required_version = "0.10.1"
#  required_version = "0.10.2"
  required_version = "0.10.3"
}
```

Also, when a `required_version` is specified up to miner version such as `~> 0.10`, it doesn't work.
However, we can go ahead with this version. It would be evolved by someone who needs that :)

**Comment by kamatama41** [comment]
However, before merging, could you add a test for this feature?
I think the test scenario becomes the following.
- create a `.tf` file includes `required_version`
  - remove the file after the test finished.
- run `tfenv install min-required` and verify installed version

**Comment by dooreelko** [comment]
Cool. I've added an integration test. Please have a look.

**Comment by tonglil** [comment]
Can `tfenv install min-required` be just `tfenv install`?

I believe using the standard `terraform {}` resource to parse out the version instead of the `tfenv`-specific `.terraform-version` will lead to greater adoption/use of `tfenv`.

**Comment by dooreelko** [comment]
@tonglil we've discussed that with @kamatama41 during my first attempt. long story short we don't want to introduce breaking changes at this stage.

**Comment by smiller171** [comment]
@dooreelko `tfenv install` could fall back to using `min-required` in the absence of a `.terraform-version` couldn't it?

**Comment by dooreelko** [comment]
@smiller171

`tfenv install min-required` doesn't need .terraform-version, instead it will parse the version from source files, terraform section.

**Comment by smiller171** [comment]
@dooreelko I'm aware, I was talking about a way for `terraform install` to fall back to `min-required` without breaking much, but I'm realizing that `min-required` needs to be much smarter before that's even considered

**Pull request merged**
