### PR TITLE
Support msys2 bash.exe

### PR DESCRIPTION
**Pull request by petemounce**
[msys2 bash](http://www.msys2.org/) didn't work for me. This patch results in great success:

```
Pete@petermounce MSYS ~
$ uname -s
MSYS_NT-10.0-WOW

Pete@petermounce MSYS ~
$ tfenv install 0.10.8
[INFO] Installing Terraform v0.10.8
[INFO] Downloading release tarball from https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_windows_amd64.zip
######################################################################## 100.0%
[INFO] Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_SHA256SUMS
tfenv: tfenv-install: [WARN] No keybase install found, skipping GPG signature verification
Archive:  tfenv_download.Q2rM0S/terraform_0.10.8_windows_amd64.zip
  inflating: /c/Users/Pete/.tfenv/versions/0.10.8/terraform.exe
[INFO] Installation of terraform v0.10.8 successful
[INFO] Switching to v0.10.8
[INFO] Switching completed

Pete@petermounce MSYS ~
$ terraform --version
Terraform v0.10.8
```

### CODE REVIEW

**Comment by petemounce** [comment]
I see the build fails, but I don't know how my change would interact with that particular failing test, given that the platform for the builds seems to be macOS?

**Comment by petemounce** [comment]
Ah - it's failing against master too.

**Comment by kamatama41** [comment]
@petemounce 
Thank you for your contribution.
It LGTM, but please note that, as I mentioned on #31, I'm not confident that all tfenv features work well on Windows because I and TravisCI don't have Windows environment.

**Comment by petemounce** [comment]
I applaud your caution, sir ;)

**Pull request merged**
