### PR TITLE
atomatically creating .terraform-version with version from backend.tf…

### PR DESCRIPTION
**Pull request by dooreelko**
… (if present)

### CODE REVIEW

**Comment by kamatama41** [comment]
Thank you @dooreelko for the contribution!
However, I think that this change should not be applied to all tfenv users because of the reasons below.

- Most of tfenv users manage their Terraform files in a SCM (probably git) repository, so automatically creating `.terraform-version` might cause an unexpected diff.
- Since we can put the `terraform` block into any `.tf` file, so all `.tf` files should be scanned not only `backend.tf`.
- According to [the official document](https://www.terraform.io/docs/configuration/terraform.html), `required_version` can be flexibly specified. So, for example, when a user specifies `~> 0.10.0`, he/she might not really want to use `0.10.0`, or what if it's `>= 0.10.0, < 0.10.6`? In other words, we cannot easily determine what version a user want to use from `required_version`.

That's why I cannot approve the PR so far. What do you think?

**Comment by dooreelko** [comment]
Hi @kamatama41 

To address your points.
1. SCM. We all use it (and we should) and imo the required minimal terraform version must be included in the repository in one form or the other. Only that way one can exclude the possibility of a human error. Ergo .terraform-version does belong to the SCM.
2. That's a fair point, i'd say we scan all tf files in the current folder. What do you think? Also this can be done in a later PR as it's not a show stopper. No software will ever be perfect :)
3. Imo, this is a user's responsibility. If they put that their minimal is 0.10.0 then it is actually a must that their terraform works correctly with 0.10.10. Though, you're right and if the user is providing a comma separated range, my changes will produce a wrong version. The downside, of course, is that if the user already has a version of terraform that is in range but not the one at the lower boundary of it, they'll have to install it, but, honestly, they either should keep their hands clean or don't mind installing multiple versions. Trying to guess for them will turn us into a microsoft or apple's autocomplete and we all know how it ends :)

I'll see what I can do about the ranged versions.

**Comment by kamatama41** [comment]
@dooreelko 
Although I considered it I cannot still approve this change because it's a big side-effect to me (all `terraform` subcommands will have a possibility to create/update `.terraform-version`) and I don't want the automation and think user should update `.terraform-version` explicitly. So I will agree if making it optional or creating a separate command to sync `.terraform-version` with the `required_version`.

**Comment by dooreelko** [comment]
Reasonable. Let's switch to the PR73

**Pull request closed without merging**
